language: ruby
cache:
  bundler: true
rvm:
- 2.3.3

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
before_install:
  - bundle install

install: true

script: rake

# branch whitelist, only for GitHub Pages
# branches:
#  only:
#  - gh-pages     # test the gh-pages branch
#  - /pages-(.*)/ # test every branch which starts with "pages-"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false


deploy:
  fqdn: kubevirt.io
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  target_branch: master
  local_dir: _site
  on:
    branch: source
