# Site settings
title: KubeVirt.io
email: non@none.com
description: > # this means to ignore newlines until "baseurl:"
  Virtual Machine Management on Kubernetes
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.kubevirt.io/" # the base hostname & protocol for your site
twitter_username: kubevirt
github_username:  kubevirt
irc: kubevirt@irc.freenode.net
Mailinglist: https://groups.google.com/forum/#!forum/kubevirt-dev
calendar: https://calendar.google.com/calendar/embed?src=18pc0jur01k8f2cccvn5j04j1g%40group.calendar.google.com&ctz=Etc%2FGMT
events: 18pc0jur01k8f2cccvn5j04j1g@group.calendar.google.com
kubevirt_version: v0.15.0
kubernetes_version: v1.10.0

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext

collections:
  labs:
    output: true
    permalink: /:collection/:path

plugins: [jekyll-paginate, jekyll-asciidoc, jekyll-redirect-from]
paginate: 5
paginate_path: "/blogs/page:num"

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
